!fix(nvim): nixpkgs 提供了 addCheck 来做合并操作。导致nvf会导致rebuild直接报错。所以全部注释掉，并使用 programs.neovim 暂时替换。
https://github.com/NotAShelf/nvf/issues/1207

https://github.com/NixOS/nixpkgs/pull/391544

       error: The option `home-manager.users.luck.programs.nvf.settings' has a type `Nvf module' that uses
       an ad-hoc `type // { check = ...; }' override, which is incompatible with
       the v2 merge mechanism.

       Please use `lib.types.addCheck` instead of `type // { check }' to add
       custom validation. For example:

         lib.types.addCheck baseType (value: /* your check */)

       instead of:

         baseType // { check = value: /* your check */; }
error: failed to build configuration: exit status 1